const express = require("express");
const createNewCase = require("../../controllers/newCase/createNewcase");
const deleteNewCase = require("../../controllers/newCase/deleteNewCase");
const getAllNewCase = require("../../controllers/newCase/getAllNewCase");
const getSingleNewCase = require("../../controllers/newCase/getSingleNewCase");
const updateNewCase = require("../../controllers/newCase/updateNewCase");
const router = express.Router();
router.post("/", createNewCase);
router.delete("/:id", deleteNewCase);
router.get("/", getAllNewCase);
router.get("/:id", getSingleNewCase);
router.put("/:id", updateNewCase);
module.exports = router;
